/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export { }

declare module 'vue' {
  export interface GlobalComponents {
    'Аь': typeof import('./components/details/Аь.md')['default']
    'ГI': typeof import('./components/details/ГI.md')['default']
    'Кх': typeof import('./components/details/Кх.md')['default']
    'Къ': typeof import('./components/details/Къ.md')['default']
    'КI': typeof import('./components/details/КI.md')['default']
    'Оь': typeof import('./components/details/Оь.md')['default']
    'ПI': typeof import('./components/details/ПI.md')['default']
    'ТI': typeof import('./components/details/ТI.md')['default']
    'Уь': typeof import('./components/details/Уь.md')['default']
    'Хь': typeof import('./components/details/Хь.md')['default']
    'ХI': typeof import('./components/details/ХI.md')['default']
    'ЦI': typeof import('./components/details/ЦI.md')['default']
    'ЧI': typeof import('./components/details/ЧI.md')['default']
    'Юь': typeof import('./components/details/Юь.md')['default']
    'Яь': typeof import('./components/details/Яь.md')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    I: typeof import('./components/details/I.md')['default']
    LetterCard: typeof import('./components/LetterCard.vue')['default']
    Loader: typeof import('./components/Loader.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionCard: typeof import('./components/SectionCard.vue')['default']
    SoundWaves: typeof import('./components/SoundWaves.vue')['default']
  }
}
